version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-landing-page
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.development.local:/app/.env.development.local
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
    env_file:
      - .env
    networks:
      - landing_network
    # Restart on failure
    restart: unless-stopped

networks:
  landing_network:
    driver: bridge