version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-landing-page
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - landing_network
    # Restart on failure
    restart: unless-stopped

  netlify-cms-proxy:
    build:
      context: .
      dockerfile: Dockerfile.netlify-cms
    container_name: netlify-cms-proxy
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    networks:
      - landing_network
    depends_on:
      - app
    # Restart on failure
    restart: unless-stopped

networks:
  landing_network:
    driver: bridge