FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies with clean npm cache
RUN npm cache clean --force && \
    npm install

COPY . .

EXPOSE 8081

CMD ["npm", "run", "netlify-cms-proxy"]
