# Configuración de construcción para Netlify
[build]
  publish = "dist"
  command = "npm run build"

# Especificar versión de Node.js
[build.environment]
  NODE_VERSION = "18.19.0"

# Redirecciones y reescrituras para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeceras para mejorar seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://unpkg.com; connect-src 'self' https://api.netlify.com;"

# Configuración de formularios
[build.processing.forms]
  # Asegúrate de que los formularios se procesen correctamente
  [build.processing.forms.netlify_forms]
    enabled = true
